# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: ''
    - name: Install Yarn
      run: npm install --global yarn
    - name: Run build bash
      run: bash build.sh
    - name: Push to gh-pages
      run: |
        git config --global user.name 'jbuendia1y'
        git config --global user.email 'jgamer669@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN_SECRET }}@github.com/${{ github.repository }}
        git add gh-pages && git commit -m "Deply gh-pages"
        git subtree push --prefix gh-pages origin gh-pages
